In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
#Naive Bayes - abordagem probabilística
#pega base de dados e faz a probabilidade
#correção laplaciana: quando todas as probabilidades de projeção dão 0
#Objetivo: analisar o risco de conceder credito 

In [4]:
base_de_risco = pd.read_csv("./risco_credito.csv")
base_de_risco

historia divida garantias     renda     risco
0           ruim   alta   nenhuma      0_15      alto
1   desconhecida   alta   nenhuma     15_35      alto
2   desconhecida  baixa   nenhuma     15_35  moderado
3   desconhecida  baixa   nenhuma  acima_35      alto
4   desconhecida  baixa   nenhuma  acima_35     baixo
5   desconhecida  baixa  adequada  acima_35     baixo
6           ruim  baixa   nenhuma      0_15      alto
7           ruim  baixa  adequada  acima_35  moderado
8            boa  baixa   nenhuma  acima_35     baixo
9            boa   alta  adequada  acima_35     baixo
10           boa   alta   nenhuma      0_15      alto
11           boa   alta   nenhuma     15_35  moderado
12           boa   alta   nenhuma  acima_35     baixo
13          ruim   alta   nenhuma     15_35      alto

# pre processamento

In [5]:
#atributos
x_credito = base_de_risco.iloc[:,0:4].values

#classe
y_credito = base_de_risco.iloc[:,4].values

In [6]:
from sklearn.preprocessing import LabelEncoder
labelenconder_historia = LabelEncoder()
labelenconder_dividas = LabelEncoder()
labelenconder_garantias = LabelEncoder()
labelenconder_renda = LabelEncoder()


In [7]:
x_credito[:,0] = labelenconder_historia.fit_transform(x_credito[:,0])
x_credito[:,1] = labelenconder_dividas.fit_transform(x_credito[:,1])
x_credito[:,2] = labelenconder_garantias.fit_transform(x_credito[:,2])
x_credito[:,3] = labelenconder_renda.fit_transform(x_credito[:,3])

In [8]:
import pickle
with open('risco_credito.pkl','wb') as f:
    pickle.dump([x_credito,y_credito], f)

# Criar algorítimo Naive Bayes

In [17]:
from sklearn.naive_bayes import GaussianNB
naive_risco_cred = GaussianNB()

#treinamento do algoritimo- gerar uma tabela de probabilidade

naive_risco_cred.fit(x_credito,y_credito)



GaussianNB()

In [10]:
x_credito

array([[2, 0, 1, 0],
       [1, 0, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 2],
       [1, 1, 1, 2],
       [1, 1, 0, 2],
       [2, 1, 1, 0],
       [2, 1, 0, 2],
       [0, 1, 1, 2],
       [0, 0, 0, 2],
       [0, 0, 1, 0],
       [0, 0, 1, 1],
       [0, 0, 1, 2],
       [2, 0, 1, 1]], dtype=object)

In [11]:
#gerar uma previsão

#em cred.predict vamos colocar os numeros que correspondem ao hitorico do cliente

previsao =naive_risco_cred.predict([[0,0,1,2],[2,0,0,0]])
previsao

array(['baixo', 'moderado'], dtype='<U8')

In [12]:
naive_risco_cred.classes_

array(['alto', 'baixo', 'moderado'], dtype='<U8')

In [13]:
naive_risco_cred.class_count_

array([6., 5., 3.])

In [14]:
naive_risco_cred.class_prior_

array([0.42857143, 0.35714286, 0.21428571])